### ISSUE TITLE
Doesnt work with youtube premium

### ISSUE THREAD

**Issue by Dianolve** [BrianPetkovsek/discord-youtube#1]
When i use it with youtube premium it stays on "browsing idle"

![as](https://user-images.githubusercontent.com/43133178/45288179-648e4000-b52d-11e8-9862-0dcedfe85249.PNG)

**Comment by BrianPetkovsek** [comment]
Problem should be fixed now with release [v1.2.0](https://github.com/BrianPetkovsek/discord-youtube/releases/tag/v1.2.0) just download run the installer again to patch.

**Comment by Dianolve** [comment]
Thanks!
