### ISSUE TITLE
Use ipc module to update RPC

### ISSUE THREAD

**Issue by MadamFoxyCoxy** [BrianPetkovsek/discord-youtube#2]
I noticed that the timer and RPC keeps being reset, and I'm wondering if we can inject some JavaScript code into the site that watches for clicks on certain elements. So if we pause, click into a new video, or change the duration it will update the RPC.

So basically the code injection will send an event to the main process via ipc, which can then be used for updating the RPC.

Just an idea I had after a quick google search. Do I think this will be easy? No. But it's just an idea.
Link to the result that gave me this idea: <https://stackoverflow.com/questions/32780726/how-to-access-dom-elements-in-electron>

I don't have any experience with Electron or YouTube's website in general, so sorry I can't help much with this.

Thanks for looking into this though <3

**Comment by BrianPetkovsek** [comment]
Its nice to see ideas and suggestions, thanks. <3

I originally looked into this while creating this app. The problem with this type implementation is when the click event sends to update RPC, the page and video isn't fully loaded yet and wont be able to get information like time duration and title. 

How RPC works is when the Discordapp is open. The RPC module will communicate with Discordapp, Discordapp then sends information to discords servers to update user activity. The [login](https://github.com/BrianPetkovsek/discord-youtube/blob/master/main.js#L118) function connects to Discordapp. We get an 'ready' event from RPC when it connects. 

Then we start a timer to send data from Youtube's video player to Discordapp. We only resend activity (checks every 5 seconds) when changes occur. Eg. a video pause, seek or change. 

I hope that explains that the timer and RPC doesn't get reset.

Youtube's player can be controlled via code. We can see if the video is paused, time duration, current time. We can also pause, unpause, seek to a time, reload the video(without refreshing the page), and set autoplay. Theres alot more but those are some of the important ones.
