### ISSUE TITLE
This is a Question, not a Issue

### ISSUE THREAD

**Issue by SerenModz21** [BrianPetkovsek/discord-youtube#3]
after i hv done npm start n the youtube application has opened, do i have to keep the cmd open?

also would i have to do npm start evertime or wud i just b able open the youtube appliction because i have pinned it to my taskbar

**Comment by BrianPetkovsek** [comment]
If you downloaded the source yourself but haven't built the electron app, you will need to keep the cmd window open. closing it will stop the application. 
If you don't want the cmd window you can build the app [here](https://github.com/BrianPetkovsek/discord-youtube#building). Once built the installer would be in the dist folder named YouTube Setup 1.2.0.exe.

If you don't want to manually build the application or are having trouble. You can always download the prebuilt application from [releases](https://github.com/BrianPetkovsek/discord-youtube/releases). Download the setup file YouTube.Setup.1.2.0.exe and run.

Once the setup is done a new app will be on the desktop. simply use it as an normal application.
