### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by ZolaKluke** [BrianPetkovsek/discord-youtube#4]
I've downloaded a version from the releases page and when I run the .exe nothing happens, I've tried both the 1.0.0 version and the 1.2.0, is there some kind of dependency needed for the release builds?

**Comment by ZolaKluke** [comment]
I just tried installing it on another computer and it worked, maybe it's something to do with my anti-virus

**Comment by BrianPetkovsek** [comment]
Anti-virus normally blocks the program. its due to the program being "new"

The only way to fix this is if i submit the program to every anti-virus company for review, or if a lot of people start using the program it will auto flag to review.
