### ISSUE TITLE
EXE

### ISSUE THREAD

**Issue by SerenModz21** [BrianPetkovsek/discord-youtube#5]
recently when ive been going on the exe, it will load fine but a few seconds later, it will open a lot of them and wont stop opening new ones and when i close the one i opened, it will close all the others. I know its not me pressing it to many times because ive tried it many times, ive even pressed it once and then pressed enter.

**Comment by BrianPetkovsek** [comment]
Hey,
I found a possible fix 
I'll upload a setup executable for you to try later today.

Thanks

**Comment by SerenModz21** [comment]
ok thank you

**Comment by SerenModz21** [comment]
ill check if its there and download it n try it

**Comment by BrianPetkovsek** [comment]
Hey @SerenModz21,
here's the possible fix could you try this out? (Just download and run)
https://drive.google.com/file/d/1PW0t1poRAZrjDER_y2XpwnB2iAVf_y83/view?usp=sharing

Thanks

**Comment by SerenModz21** [comment]
hey sorry its been a few days, ill try it for you now

**Comment by SerenModz21** [comment]
so ive just tried it and its working but wen u pause it (press it 2 pause), it loads another one but it only loads that 1 which can as ive seen right now anyway but that one.

It doesn't look like a big problem like the other one was but currently i have only one other tab opening which ive easily been able to close.

If i find anymore problems for you, ill let you know on here.

**Comment by SerenModz21** [comment]
ive just been back on it after leaving it for a few hours and it has started doing it again

**Comment by BrianPetkovsek** [comment]
Sorry i have no clue on why the problem is happening.
i cant make any changes until i see the problem, a video of the problem happening might help.

however there's a chance I cant fix the bug because it might be system isolated.
