### ISSUE TITLE
Timer is not working on exe

### ISSUE THREAD

**Issue by LovecraftianMordo** [BrianPetkovsek/discord-youtube#6]
I installed the version 1.2.0. Its working well but there is just one problem: Timer is not working. Its always stucking in 0:00. How can i fix that? 

Also a video tutorial for installation can be very useful though. 

Thanks for this software :)

**Comment by BrianPetkovsek** [comment]
I added a fix, a new version should be out in a couple of days.

Thanks.

**Comment by SerenModz21** [comment]
@LovecraftianMordo the installation is easy my friend, you just download it and then open it and its all setup

**Comment by BrianPetkovsek** [comment]
@LovecraftianMordo sorry it's taking longer than expected to release the new update, I have exams this for the next couple of weeks. a fix for the timer can be installed from this setup file just download and run.
https://drive.google.com/uc?export=download&id=1PW0t1poRAZrjDER_y2XpwnB2iAVf_y83

**Comment by LovecraftianMordo** [comment]
@BrianPetkovsek thank u so much. it was very helpful ^^
