### ISSUE TITLE
Always shows 0:00 remaining

### ISSUE THREAD

**Issue by TheArcaneBrony** [BrianPetkovsek/discord-youtube#7]
Time remaining in Discord rich prescence always shows 0:00, did youtube change something?
https://i.imgur.com/n2gLUlH.png

**Comment by BrianPetkovsek** [comment]
Hello @TheArcaneBrony
fixed in version 1.2.2.

Should update automatically 
however if it doesn't download the update from. 

https://github.com/BrianPetkovsek/discord-youtube/releases/tag/v1.2.2
