### ISSUE TITLE
Can't login in YouTube client

### ISSUE THREAD

**Issue by wiesmin138** [BrianPetkovsek/discord-youtube#8]
![obraz](https://user-images.githubusercontent.com/54535486/77643508-c5d70200-6f5f-11ea-95ea-acc6035d70f5.png)

**Comment by BrianPetkovsek** [comment]
Hi, @wiesmin138 

Thanks for opening this issue.
I just released a new version today that fixes it.
You can download it here or open the app and wait for the app to finish the download for you.

[discord-youtube-v1.3.4](https://github.com/BrianPetkovsek/discord-youtube/releases/latest)
